services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: compute-xstrk
      POSTGRES_USER: xstrk
      POSTGRES_PASSWORD: xstrk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
